topoguide/itineraires/urls.py
from django.urls import path
from . import views

app_name = 'itineraires'
urlpatterns = [
    path('itineraires/', views.itineraires, name = 'itineraires'),
    path('sorties/<str:itineraire_id>/', views.sorties, name='sorties'),
    path('sortie/<str:sortie_id>/', views.sortie, name='sortie'),
    path('nouvelle_sortie/', views.nouvelle_sortie, name='nouvelle_sortie'),
    path('modifier/<str:sortie_id>/', views.modif_sortie, name='modif_sortie')
]

topoguide/topoguide/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('itineraires.urls'))
]

topoguide/itineraires/models.py
from django.contrib.auth.models import User
from django.db import models


class Itineraire(models.Model):
    """
    Une classe itinéraire qui comprend différentes informations

    Args:
        models (): Model

    """
    title = models.CharField(max_length=200)
    departure = models.CharField(max_length=200)
    description = models.TextField(max_length=500)
    altitude_dep = models.IntegerField(default=0)
    altitude_min = models.IntegerField(default = 0)
    altitude_max = models.IntegerField(default = 0)
    height_dif_pos = models.IntegerField(default=0)
    height_dif_neg = models.IntegerField(default=0)
    # une durée au format 00:00:00 (h:min:sec)
    duration = models.DurationField()
    difficulty = models.CharField(choices = [('1', '1'),('2', '2'),('3','3'),('4', '4'),('5','5')], max_length=3)
        
    def __str__(self):
        return self.title

class Sortie(models.Model):
    """
    Une classe sortie avec les informations associées

    Args:
        models (): Model

    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    itineraire = models.ForeignKey(Itineraire, on_delete=models.CASCADE)
    date = models.DateField()
    duration = models.DurationField()
    people = models.IntegerField(default = 1)
    group_exp = models.CharField(choices= [('tous débutants','tous débutants'), ('tous expérimentés','tous expérimentés'), ('mixte','mixte' )], max_length=100 )
    weather = models.CharField(choices = [('bonne','bonne'), ('moyenne','moyenne'), ('mauvaise','mauvaise')], max_length=100)
    difficulty = models.CharField(choices = [('1', '1'),('2', '2'),('3','3'),('4', '4'),('5','5')], max_length=3)
    
    def __str__(self):
        return self.itineraire.title + " by " + self.user.username  

topoguide/itineraires/forms.py
from django.forms import ModelForm

from itineraires.models import Sortie

class SortieForm(ModelForm):
    """
    Un forumaire pour ajouter une sortie à la base de donnée

    Args:
        ModelForm :  un ModelForm 
    """
    class Meta:
        model = Sortie
        fields = ['itineraire', 'date', 'duration', 'people', 'group_exp', 'weather', 'difficulty']

class ModifSortieForm(ModelForm):
    """
    Un formulaire pour modifier une sortie déjà présente

    Args:
        ModelForm (): un ModelForm
    """
    class Meta:
        model = Sortie
        fields = ['itineraire', 'date', 'duration', 'people', 'group_exp', 'weather', 'difficulty']

topoguide/itineraires/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required

from itineraires.models import Itineraire, Sortie
from itineraires.forms import *


@login_required()
def itineraires(request):
    """
    Une vue itineraires qui comprend la liste des itinéraires de la base données

    Args:
        request (): requete utilisateur

    Returns:
        la page html associée à la vue 
    """
    itineraires_list = Itineraire.objects.order_by('-title')
    context = {'itineraires_list': itineraires_list}
    return render(request, 'itineraires/itineraires.html', context)


@login_required()
def sorties(request, itineraire_id):
    """
    Une vue sorties qui comprend la liste des sorties pour un itinéraire donné

    Args:
        request (): requete utilisateur
        itineraire_id (): l'itineraire dont on veut voir les sorties

    Returns:
        la page html associée à la vue
    """
    itineraire = get_object_or_404(Itineraire, pk=itineraire_id)
    return render(request,'itineraires/sorties.html', {'itineraire' : itineraire})


@login_required()
def sortie(request, sortie_id):
    """
    Une vue sortie qui comprend les informations relatives à une sortie, telle qu'à pu le rentrer un utilisateur

    Args:
        request (): requete utilisateur
        sortie_id (): la sortie dont on veut voir les informations

    Returns:
        la page html associée à la vue
    """
    sortie = get_object_or_404(Sortie, pk=sortie_id)
    return render(request,'itineraires/sortie.html', {'sortie' : sortie} )


@login_required()
def nouvelle_sortie(request):
    """
    Une vue nouvelle_sortie qui permet de créer une nouvelle sortie dans la base de données

    Args:
        request (): requete utilisateur

    Returns:
        Le formulaire de saisie dans le cas d'une requete get, ou bien la création d'une nouvelle sortie et la redirection vers la page itinéraires une fois le formulaire complété
    """
    if request.method == 'POST':
        form = SortieForm(request.POST)
        if form.is_valid():
            #on fait en sorte que le user associé à la sortie crée soit le user connecté à la session
            nouvelle_sortie = form.save(commit=False)
            nouvelle_sortie.user = request.user
            nouvelle_sortie.save()
            # on redirige vers la page itineraire
            return redirect('/itineraires/')
    elif request.method == 'GET':
        # on crée puis affiche le formulaire à compléter
        form = SortieForm()
    return render(request, 'itineraires/nouvelle_sortie.html', {'form' : form})

@login_required()
def modif_sortie(request, sortie_id):
    """
    Une vue modif_sortie qui permet de modifier une sortie déjà présente dans la base de données

    Args:
        request (): requete utilisateur
        sortie_id (): l'identifiant de la sortie que l'on veut modifier

    Returns:
        la sortie est modifiée et une redirection vers la page itineraire
    """
    sortie = get_object_or_404(Sortie, pk = sortie_id)
    if request.method == 'GET':
        # on crée puis affiche le forulaire à compléter, avec une instance de sortie
        form = ModifSortieForm(instance=sortie)
    elif request.method == 'POST':
        form = ModifSortieForm(request.POST, instance=sortie)
        if form.is_valid() and sortie.user == request.user:
            # on vérifie que le user connecté soit le même que celui qui a crée la sortie
            modif_sortie = form.save(commit=False)
            modif_sortie.user = request.user
            modif_sortie.save()
            # redirection vers la page itineraires
            return redirect('/itineraires/')
    return render(request, 'itineraires/modif_sortie.html', {'form' : form})
            

topoguide/itineraires/templates/itineraires/base.html
<!doctype html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'itineraires/base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    
</head>

<body>
    {% block body  %}{% endblock body  %}

</body>

topoguide/itineraires/templates/itineraires/itineraires.html
<!doctype html>

{% extends 'itineraires/base.html' %}

{% block body  %}

<h1>Itineraires</h1>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Topoguide</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'itineraires:nouvelle_sortie' %}">Ajouter une nouvelle sortie</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Se déconnecter</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<div class="transbox">

    <table class = "table">
        <tr>
            <th>Nom</th>
            <th>Départ</th>
            <th>Durée estimée</th>
            <th>Difficultée estimée</th>
        </tr>

        {% if itineraires_list %}
    
            {% for itineraire in itineraires_list %}

                <tr>
                    <td><a href="{% url 'itineraires:sorties' itineraire.id %}">{{itineraire.title}}</a></td>
                    <td>{{itineraire.departure}}</td>
                    <td>{{itineraire.duration}}</td>
                    <td>{{itineraire.difficulty}}/5</td>
                </tr>

            {% endfor %}

        {% else %}
        <p>No itineraire are available.</p>
        {% endif %}
    </table>

</div>

{% endblock body  %}

topoguide/itineraires/templates/itineraires/modif_sortie.html
<!doctype html>

{% extends 'itineraires/base.html' %}

{% block body %}

    <h1>Modifier la sortie {{ sortie.itineraire.title }}</h1>

    <div class="transbox">

    {% if request.user != sortie.user %}
    <p>You are not the user corresponding to the sortie. Thus, you cannot modify it.</p>

    {% else %}
        <form method="post" action="{% url 'itineraires:modif_sortie' form.instance.id %}">
            {% csrf_token %}
            
            {{ form }}
            
            <input type="submit" value="Modifier la sortie">
        </form>
    {% endif %}

    </div>

{% endblock body %}

topoguide/itineraires/templates/itineraires/nouvelle_sortie.html
<!doctype html>

{% extends 'itineraires/base.html' %}

{% block body %}

    <h1>Ajouter une sortie {{ sortie.itineraire.title }}</h1>

    <form method="post" action="{% url 'itineraires:nouvelle_sortie' %}">
        {% csrf_token %}
        
        {{ form }}
        
        <input type="submit" value="Ajout d'une sortie">
    </form>

{% endblock body %}

topoguide/itineraires/templates/itineraires/sortie.html
<!doctype html>

{% extends 'itineraires/base.html' %}

{% block body  %}

<h1>Sortie {{ sortie.itineraire.title }}</h1>


<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Topoguide</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'itineraires:itineraires' %}">Itinéraires</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'itineraires:sorties' sortie.itineraire.id %}">Retour à la liste de sorties</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'itineraires:nouvelle_sortie' %}">Ajouter une nouvelle sortie</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'itineraires:modif_sortie' sortie.id %}">Modifier la sortie</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Se déconnecter</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


<h2>by {{sortie.user}}</h2>

<div class="transbox">

    <table class = "table">
        <tr>
            <th></th>
            <th>Réalisé</th>
            <th>Prévu</th>

        
        <tr>
            <th>Date</th>
            <td>{{sortie.date}}</td>
            <td> / </td>
        </tr>
        
        <tr>
            <th>Durée réelle</th>
            <td>{{sortie.duration}}</td>
            <td>{{sortie.itineraire.duration}}</td>
        </tr>

        <tr>
            <th>Nombre de participants</th>
            <td>{{sortie.people}}</td>
            <td> / </td>
        </tr>

        <tr>
            <th>Niveau des randonneurs</th>
            <td>{{sortie.group_exp}}</td>
            <td> / </td>
        </tr>

        <tr>
            <th>Météo</th>
            <td>{{sortie.weather}}</td>
            <td> / </td>
        </tr>   

        <tr>
            <th>Difficultée</th>
            <td>{{sortie.difficulty}}/5</td>
            <td>{{sortie.itineraire.difficulty}}/5</td>
        </tr>
    </table>

</div>

{% endblock body  %}

topoguide/itineraires/templates/itineraires/sorties.html
<!doctype html>

{% extends 'itineraires/base.html' %}

{% block body %}
<h1>Sorties  {{ itineraire.title }}</h1>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Topoguide</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'itineraires:itineraires' %}">Itinéraires</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'itineraires:nouvelle_sortie' %}">Ajouter une nouvelle sortie</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Se déconnecter</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


<div class="transbox">

  <p>{{itineraire.description}}</p>

  <table class = "table">
    <tr>
        <th>Lieu de départ</th>
        <td>{{itineraire.departure}}</td>
    </tr>
    
    <tr>
        <th>Altitude de départ</th>
        <td>{{itineraire.altitude_dep}} mètres</td>
    </tr>

    <tr>
        <th>Altitude minimale</th>
        <td>{{itineraire.altitude_min}} mètres</td>
    </tr>

    <tr>
        <th>Altitude maximale</th>
        <td>{{itineraire.altitude_max}} mètres</td>
    </tr>

    <tr>
        <th>Dénivelé positif</th>
        <td>+{{itineraire.height_dif_pos}} mètres</td>
    </tr>   

    <tr>
        <th>Dénivelé négatif</th>
        <td>-{{itineraire.height_dif_neg}} mètres</td>
    </tr>

    <tr>
      <th>Durée estimée</th>
      <td>{{itineraire.duration}}(h:min:sec)</td>
    </tr>

    <tr>
      <th>Difficultée</th>
      <td>{{itineraire.difficulty}}/5</td>
    </tr>

</table>


  {% if itineraire.sortie_set.all %}
      <h3>Liste des sorties</h3>

      <table class = "table">
          <tr>
              <th>Par</th>
              <th>Date</th>
              <th></th>
          </tr>

              {% for sortie in itineraire.sortie_set.all %}
                  <tr>
                      <td>{{ sortie.user }}</td>
                      <td>{{ sortie.date }}</td>
                      <td><a href="{% url 'itineraires:sortie' sortie.id %}">Consulter</a></td>
                  </tr>
              {% endfor %}

      </table>

  {% else %}
      <p>Il n'y a pas de sorties pour cet itineraire.</p>
  {% endif %}
</div>
{% endblock body %}